// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKEViQneHjC84xnekbk_8YrOZJcYhsVY',
    appId: '1:709060745209:web:b15d26b120146200fc0f28',
    messagingSenderId: '709060745209',
    projectId: 'chat-app-4d363',
    authDomain: 'chat-app-4d363.firebaseapp.com',
    storageBucket: 'chat-app-4d363.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTk0UIIYOLKRJ7jIw8Ud8JS0roZDT244',
    appId: '1:709060745209:android:271dd6eb440bf656fc0f28',
    messagingSenderId: '709060745209',
    projectId: 'chat-app-4d363',
    storageBucket: 'chat-app-4d363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrrhQQyiZ4vpbPOnDdxdWZbSWgKKH-Egs',
    appId: '1:709060745209:ios:631b4c10f1f2dee5fc0f28',
    messagingSenderId: '709060745209',
    projectId: 'chat-app-4d363',
    storageBucket: 'chat-app-4d363.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrrhQQyiZ4vpbPOnDdxdWZbSWgKKH-Egs',
    appId: '1:709060745209:ios:631b4c10f1f2dee5fc0f28',
    messagingSenderId: '709060745209',
    projectId: 'chat-app-4d363',
    storageBucket: 'chat-app-4d363.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPKEViQneHjC84xnekbk_8YrOZJcYhsVY',
    appId: '1:709060745209:web:63cda6937d0b7428fc0f28',
    messagingSenderId: '709060745209',
    projectId: 'chat-app-4d363',
    authDomain: 'chat-app-4d363.firebaseapp.com',
    storageBucket: 'chat-app-4d363.appspot.com',
  );
}
